---
- name: "Go to logstash project"
  command: oc project {{ logstash_project }}

- name: delete items
  shell: "oc delete {{ item }}  -n {{ logstash_project }}|| true"
  with_items:
  - all --selector app=logstash
  - templates logstash-template
  - configmap logstash-config
  - configmap logstash-patterns

- name: "Delete tmp files from remote"
  file: path=/tmp/{{ item }} state=absent
  with_items:
  - logstash-template.yaml
  - conf.d
  - patterns.d
