---
- name: "Go to logstash project"
  command: "oc project {{ logstash_project }}"

- name: delete old configmaps
  shell: "oc delete configmap logstash-config|| true"

- name: "Copy logstash client configs to the remote"
  copy: src={{ item }} dest=/tmp/conf.d/
  with_fileglob:
  - "{{ role_path }}/files/conf.d/*"

- name: "Create logstash client config configMaps"
  command: "oc create configmap logstash-config --from-file=/tmp/conf.d -n {{ logstash_project }}"

- name: delete old pattenrs
  shell: "oc delete configmap logstash-patterns  -n {{ logstash_project }}|| true"

- name: "Copy logstash patterns to the remote"
  copy: src={{ item }} dest=/tmp/patterns.d/
  with_fileglob:
  - "{{ role_path }}/files/patterns.d/*"

- name: "Create logstash patterns configMaps"
  command: "oc create configmap logstash-patterns --from-file=/tmp/patterns.d  -n {{ logstash_project }}"

#- name: "Deploy new Logstash"
#  command: "oc deploy logstash --latest"
